version: "3"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - mongo-db
        ports:
            - "3000:3000"

    mongo-db:
        image: mongo
        ports:
            - "27017:27017"
        container_name: mongo
